# Generated by Django 2.1.3 on 2018-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181220_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='fees',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
