# Generated by Django 2.1.3 on 2018-12-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181220_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adhaar',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
